frontend/models/Ticket.php
<?php

namespace frontend\models;

use Yii;

/**
 * This is the model class for table "ticket".
 *
 * @property int $id
 * @property string $subject
 * @property string $from
 * @property string|null $body
 * @property string|null $date
 * @property integer|null $status
 */
class Ticket extends \yii\db\ActiveRecord
{
    const STATUS_CLOSED = 2;
    const STATUS_WAIT = 1;
    const STATUS_NEW = 0;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'ticket';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['subject', 'from'], 'required'],
            [['body'], 'string'],
            [['subject', 'from'], 'string', 'max' => 255],
            [['date'], 'string', 'max' => 100],
            [['status'], 'number']
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'subject' => Yii::t('app', 'Subject'),
            'from' => Yii::t('app', 'From'),
            'body' => Yii::t('app', 'Body'),
            'date' => Yii::t('app', 'Date'),
            'statusLabel' => Yii::t('app', 'Status'),
        ];
    }

    public function getStatusLabel()
    {
        switch ($this->status) {
            case self::STATUS_WAIT:
                return '<span class="badge badge-primary">Waiting</span>';
            case self::STATUS_CLOSED:
                return '<span class="badge badge-success">Closed</span>';
            default:
                return '<span class="badge badge-info">New</span>';
        }
    }
}

frontend/controllers/TicketController.php
<?php

namespace frontend\controllers;

use frontend\models\Ticket;
use frontend\models\TicketMessage;
use frontend\models\TicketMessageForm;
use frontend\models\TicketSearch;
use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * TicketController implements the CRUD actions for Ticket model.
 */
class TicketController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Ticket models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new TicketSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Ticket model.
     * @param int $id ID
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView(int $id)
    {
        $form = new TicketMessageForm();
        if (Yii::$app->request->isPost && $form->load(Yii::$app->request->post())) {
            if ($form->sendMail($id)) {
                $form = new TicketMessageForm();
                Yii::$app->session->setFlash('success', 'Email send!');
            } else {
                Yii::$app->session->setFlash('danger', 'Can`t send email!');
            }
        }
        return $this->render('view', [
            'model' => $this->findModel($id),
            'messages' => TicketMessage::find()->where(['ticket_id' => $id])->orderBy(['id' => SORT_DESC])->all(),
            'form_model' => $form
        ]);
    }

    /**
     * Creates a new Ticket model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Ticket();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Ticket model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Ticket model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionClose($id)
    {
        $model = $this->findModel($id);
        if ($model) {
            $model->status = Ticket::STATUS_CLOSED;
            $model->save();
            Yii::$app->session->setFlash('success', 'Ticket closed!');
        }

        return $this->redirect(['view', 'id' => $id]);
    }

    /**
     * Finds the Ticket model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Ticket the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Ticket::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

frontend/views/ticket/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\Ticket */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="ticket-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'subject')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'from')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'date')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/ticket/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\TicketSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="ticket-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'subject') ?>

    <?= $form->field($model, 'from') ?>

    <?= $form->field($model, 'body') ?>

    <?= $form->field($model, 'date') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/ticket/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model frontend\models\Ticket */

$this->title = 'Create Ticket';
$this->params['breadcrumbs'][] = ['label' => 'Tickets', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="ticket-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/ticket/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel frontend\models\TicketSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Tickets';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="ticket-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php Pjax::begin(); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [

            'id',
            'subject',
            'from',
//            'body:raw',
            [
                'attribute' => 'status',
                'filter' => [
                    0 => 'New',
                    1 => 'Waiting',
                    2 => 'Closed'
                ],
                'format' => 'raw',
                'value' => 'statusLabel'
            ],
            'date',

            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{view} {delete}'
            ],
        ],
    ]); ?>

    <?php Pjax::end(); ?>

</div>

frontend/views/ticket/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model frontend\models\Ticket */

$this->title = 'Update Ticket: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Tickets', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="ticket-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/ticket/view.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model frontend\models\Ticket */

$this->title = $model->subject;
$this->params['breadcrumbs'][] = ['label' => 'Tickets', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="ticket-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'subject',
            'from',
            'statusLabel:raw',
            'date',
        ],
    ]) ?>
    <?php if ($model->status !== \frontend\models\Ticket::STATUS_CLOSED) : ?>
        <a href="<?= \yii\helpers\Url::to(['ticket/close', 'id' => $model->id]) ?>" class="btn btn-success">Close
            ticket</a>
    <?php endif; ?>
    <hr>
    <h3>Messages:</h3>

    <div class="messages-wrapper">
        <div class="messages-body">
            <?php if (isset($messages)) { ?>
                <?php foreach ($messages as $message) : ?>
                    <div class="message-item <?= $message->from !== $model->from ? 'output' : '' ?>">
                        <div class="message-body"><?= $message->message ?></div>
                        <div class="message-date"><?= $message->date ?></div>
                    </div>

                <?php endforeach; ?>
            <?php } else { ?>
                Nothing here yet
            <?php } ?>
        </div>
        <div class="messages-form">
            <div class="row">
                <div class="col-md-2"></div>
                <div class="col-md-8">
                    <?php $form = ActiveForm::begin(); ?>
                    <?= $form->field($form_model, 'from')->hiddenInput(['value' => $model->from])->label(false); ?>
                    <?= $form->field($form_model, 'subject') ?>
                    <?= $form->field($form_model, 'body')->textarea(['rows' => 6]) ?>
                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>
                    <?php ActiveForm::end(); ?>
                </div>
                <div class="col-md-2"></div>
            </div>
        </div>
    </div>
</div>

<style>
    .messages-body {
        max-height: 300px;
        overflow-y: auto;
    }
    .messages-body {
        background-color: #eee;
        padding: 10px 4px;
    }
    .message-item {
        padding: 4px 14px;
        background-color: #0f6674;
        color: #fff;
        margin-bottom: 20px;
        width: fit-content;
        border-radius: 8px;
    }
    .message-item.output {
        background-color: #1c7430;
        margin-left: auto;
    }
    .message-item .message-date {
        color: #FFFFFF5B;
        font-size: 12px;
    }
</style>